# Generated by Django 4.2 on 2025-09-14 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_record_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('variant_titles', models.JSONField(default=list)),
                ('authors', models.JSONField(default=list)),
                ('publication_years', models.JSONField(default=list)),
                ('genres', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('isbn', models.JSONField(default=list)),
                ('other_fields', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result_ids', models.JSONField(default=list)),
                ('num_results', models.IntegerField()),
            ],
        ),
    ]
